[tool.poetry]
name = "tempmon"
version = "0.4.0"
description = "A simple CPU and GPU temperature monitor."
authors = ["cubic-unit"]

[tool.poetry.dependencies]
python = "^3.8"
elevate = "^0.1.3"
dearpygui = "0.3.6"
pythonnet = "^2.5.1"

[tool.poetry.dev-dependencies]
elevate = "^0.1.3"
dearpygui = "0.3.6"
pythonnet = "^2.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
